### ISSUE TITLE
What values of z to use to calculate beam propagation?

### ISSUE THREAD

**Issue by rxshira** [rxshira/modematching#1]
The idea is to calculate how the beam propagates through the free space segments of the beam path. For that, for each free space segment, I calculated the ABCD matrix of all the things that were before that segment (free spaces and lenses). Then, based on that matrix and the initial "z0" and "w0," I calculated "q(z)" for all the "z" values in the free space and with it the w(z).

I had some questions:

1) Is it the right way to calculate the "w(z)"?
2) I wasn't sure what values of z to use. Let me try to use an example to clarify:
Let's say that I have a first free space segment of 10cm, followed by a lens and then another free space segment of 30 cm. I'd like to calculate the beam propagation in the second segment (the 30 cm segment). My idea was to calculate the ABCD matrix of the first free space and the lens, and now I want to calculate the q(z) and w(z).

At this point, I'm not sure what values of "z" to use. Should it start at 0cm or 10cm for "w(z)" of the second segment? (So, in line 119, use the values indicated in 117 or 118).

Thank you!

**Comment by pacosalces** [comment]
I'm not sure I understand your question 1, but I'm afraid you need to incorporate other elements apart from the single free-space segments into that ABCD. 

To answer 2., an ABCD matrix will take you from z1 to z2. We want all values of z from beginning to end of this beam path, call that z_arr = [z0, z1, ..., zN]. You can construct an end-to-end matrix to know what the beam looks like around the output, and that's likely good enough to start, but we want a code that stops at z_j and constructs the right ABCD up to that point, then get the w(z_j).

I hope this is helpful, and if not I can take a look at the code and work through an example.

**Comment by rxshira** [comment]
Thank you so much! Yes, this was very helpful! I will finish mapping out the entire beam path by the end of the coming week. 

Also, I was curious about the distances on the schematic. Are they in inches/cm, or is there a unit conversion I need to account for? Thanks again!

**Comment by pacosalces** [comment]
They are in inches! So you have to convert and all the code should be in meters.

**Comment by rxshira** [comment]
Got it! Thank youu so much.
